name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.1.app
    
    - name: Get version
      id: version
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi
    
    - name: Build Release
      run: make release
    
    - name: Create App Bundle
      run: |
        # The make release command should have created the app bundle
        cd dist
        ls -la
        # Verify the zip was created
        test -f GClouder.zip || exit 1
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || github.ref }}
        name: GClouder ${{ steps.version.outputs.VERSION }}
        body: |
          ## Changes in this Release
          
          ### Installation
          1. Download `GClouder.zip` below
          2. Unzip the file
          3. Drag `GClouder.app` to your Applications folder
          4. Launch GClouder from Applications
          
          ### Requirements
          - macOS 13.0 (Ventura) or later
          - Google Cloud SDK installed
        files: |
          dist/GClouder.zip
        draft: false
        prerelease: false 